spring.application.name=parkping
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=false

telegram.bot.token=8440191247:AAHDNBFjIcBudJjrvqyl0PW_0RGAKdkzhjw
telegram.chat.id=7234149296